FROM mcr.microsoft.com/devcontainers/base:ubuntu-24.04

# use this Dockerfile to install additional tools you might need, e.g.
# RUN apt-get update && export DEBIAN_FRONTEND=noninteractive \
#     && apt-get -y install --no-install-recommends <your-package-list-here>

RUN apt update
RUN apt install python3 -y
RUN apt install pip -y
RUN pip install pandas --break-system-packages
RUN pip install matplotlib --break-system-packages
RUN pip install scipy --break-system-packages
RUN pip install seaborn --break-system-packages